### ISSUE TITLE
Templating environment variables

### ISSUE THREAD

**Issue by zacdezgeo** [Anagraph/yogrt#18]
I really like the syntax used for our dbt profiles by using the same env file. It helps have a single place where credentials are defined and ignored in our git history. Other uses are in shell scripts that call psql commands. 
```
default:
  target: default
  outputs:
    default:
      type: postgres
      host: "{{env_var('PG_HOST')}}"
      user: "{{env_var('PG_USER')}}"
      password: "{{env_var('PG_PASSWORD')}}"
      port: "{{env_var('PG_PORT') | as_number }}"
      dbname: "{{env_var('PG_DATABASE')}}"
      schema: "{{env_var('PG_SCHEMA')}}"
      threads: "{{env_var('DBT_THREADS') | as_number }}"
```
The equivalent feature is not available yet in yogrt, we have to copy the credentials into the secrets.yaml or write some custom script to modify the file at runtime. Templating like with dbt would be better.
